import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      all: false,
      include: ['packages/*/src/**/*.ts'],
      exclude: ['**/*.d.ts', 'packages/*/test/**', 'packages/*/src/**/fixtures/**'],
      reporter: ['text', 'json', 'json-summary'],
      reportsDirectory: './coverage',
    },
    projects: [
      'packages/core',
      'packages/event',
      'packages/model-caller',
      'packages/permission',
      'packages/schema',
      'packages/tools',
      'packages/tools-fs',
      'packages/tools-shell',
      'packages/tools-web',
      'packages/tools-git',
      'packages/tools-search',
      'packages/tools-agent',
      'packages/tool-saga',
      'packages/step-executor',
      'packages/session',
      'packages/store-memory',
      'packages/store-drizzle',
      'packages/store-drizzle-pg',
      'packages/sandbox',
      'packages/sandbox-host',
      'packages/sandbox-process',
      'packages/sandbox-container',
      'packages/knowledge',
      'packages/security',
      'packages/plugin',
      'packages/lsp',
      'packages/provider-openai-compatible',
      'packages/provider-deepseek',
      'packages/provider-anthropic',
      'packages/provider-ollama',
    ],
  },
});
