// Re-export from @vinhnt-sdk/tools
export { createReadFileTool, createWriteFileTool, createEditFileTool, createApplyPatchTool, createListDirectoryTool } from "@vinhnt-sdk/tools";
export { createShellTool } from "@vinhnt-sdk/tools";
export type { ShellToolConfig } from "@vinhnt-sdk/tools";
export { createGitStatusTool, createGitDiffTool, createGitLogTool, createGitCommitTool } from "@vinhnt-sdk/tools";
export { createGlobFilesTool, createGrepFilesTool } from "@vinhnt-sdk/tools";
export { createWebFetchTool } from "@vinhnt-sdk/tools";
export { ToolRegistry } from "@vinhnt-sdk/tools";
export type { ToolPermissionRule, ToolMaterialization } from "@vinhnt-sdk/tools";
export { createCodingDomain } from "@vinhnt-sdk/tools";
export type { DomainManifest } from "@vinhnt-sdk/tools";
export { defineTool, toolToDefinition, zodSchemaToNestedJsonSchema } from "@vinhnt-sdk/tools";
export type { Tool, ToolConfig } from "@vinhnt-sdk/tools";
export { LazyToolRegistry } from "@vinhnt-sdk/tools";
export type { LazyToolEntry } from "@vinhnt-sdk/tools";
export type { ApprovalHandler } from "@vinhnt-sdk/tools";
export { ToolSandbox, signalToToolContext } from "@vinhnt-sdk/tools";
export type { SandboxConfig } from "@vinhnt-sdk/tools";
export { FileReadTracker } from "@vinhnt-sdk/tools";
export { generateDiff } from "@vinhnt-sdk/tools";
export type { UnifiedDiff } from "@vinhnt-sdk/tools";
export { InMemoryFileHistory } from "@vinhnt-sdk/tools";
export { createFileHistoryHook } from "@vinhnt-sdk/tools";
export { readImageToContentParts, createReadImageTool } from "@vinhnt-sdk/tools";
export { createQuestionTool } from "@vinhnt-sdk/tools";
export type { QuestionInput, QuestionHandler } from "@vinhnt-sdk/tools";
export { createTodoWriteTool } from "@vinhnt-sdk/tools";
export { createWebSearchTool } from "@vinhnt-sdk/tools";
export type { WebSearchToolConfig } from "@vinhnt-sdk/tools";
export { createToolSearchTool } from "@vinhnt-sdk/tools";
export type { ToolSearchInput, ToolSearchResult } from "@vinhnt-sdk/tools";
export { ToolProviderRegistry } from "@vinhnt-sdk/tools";
export type { ToolProvider } from "@vinhnt-sdk/tools";
export { BuiltinToolProvider, ToolFileProvider, ToolFileLoader, AgentToolProvider, SkillToolProvider } from "@vinhnt-sdk/tools";
export type { BuiltinToolConfig } from "@vinhnt-sdk/tools";
export { createToolProviderRegistry, createToolProvider } from "@vinhnt-sdk/tools";

// Core-only: kernel integration
export { ToolRuntime } from "./runtime.js";
export type { ToolRuntimeConfig } from "./runtime.js";
export { createKernelTools, createPluginToolHook } from "./bridge.js";
export { registerProviderTools } from "./provider-helpers.js";
