export type ControlType =
  | "text" | "password" | "number" | "toggle"
  | "select" | "multi-select" | "code" | "color" | "keybinding";

export interface ConfigFieldMeta {
  key: string;
  label: string;
  description?: string;
  group: string;
  control: ControlType;
  placeholder?: string;
  default?: unknown;
  options?: { value: string; label: string }[];
  validation?: {
    required?: boolean;
    optional?: boolean;
    min?: number;
    max?: number;
    pattern?: string;
    secret?: boolean;
    integer?: boolean;
    fallback?: unknown;
  };
  advanced?: boolean;
  order?: number;
  children?: ConfigFieldMeta[];
  arrayItem?: ConfigFieldMeta;
  recordValue?: ConfigFieldMeta;
}

export interface ConfigGroup {
  id: string;
  label: string;
  description?: string;
  icon?: string;
  fields: ConfigFieldMeta[];
  advanced?: boolean;
}

/**
 * Default shell options — convenience only.
 * User tự extend: `config.shellOptions = [...DEFAULT_SHELL_OPTIONS, { value: "nushell", label: "Nushell" }]`
 */
export const DEFAULT_SHELL_OPTIONS: { value: string; label: string }[] = [
  { value: "bash", label: "Bash" },
  { value: "zsh", label: "Zsh" },
  { value: "pwsh", label: "PowerShell Core" },
  { value: "powershell", label: "Windows PowerShell" },
];

/**
 * Default agent modes — convenience only.
 * User tự extend: `config.agentModes = [...DEFAULT_AGENT_MODES, { value: "custom", label: "Custom Mode" }]`
 */
export const DEFAULT_AGENT_MODES: { value: string; label: string }[] = [
  { value: "build", label: "Build (full access)" },
  { value: "plan", label: "Plan (read-only)" },
];

export const CONFIG_GROUPS: ConfigGroup[] = [
  {
    id: "general",
    label: "General",
    icon: "settings",
    fields: [
      {
        key: "defaultProvider",
        label: "Default Provider",
        description: "The AI provider to use by default. Leave empty (no default) — the model is resolved from configured providers; use a custom provider id or a local server when configured.",
        group: "general",
        control: "text",
        placeholder: "your configured provider id",
        default: "",
        order: 1,
      },
      {
        key: "defaultModel",
        label: "Default Model",
        description: "The model to use by default. Leave empty to let the provider's live /models list decide.",
        group: "general",
        control: "text",
        placeholder: "",
        default: "",
        order: 2,
      },
      {
        key: "smallModel",
        label: "Small Model",
        description: "A cheaper/faster model for simple tasks. Leave empty to let the provider's live /models list decide.",
        group: "general",
        control: "text",
        placeholder: "",
        default: "",
        order: 3,
      },
      {
        key: "defaultAgent",
        label: "Default Agent",
        description: "The agent to use when none is specified",
        group: "general",
        control: "select",
        options: [
          { value: "build", label: "Build (full access)" },
          { value: "plan", label: "Plan (read-only)" },
        ],
        default: "build",
        order: 4,
      },
      {
        key: "auto",
        label: "Auto Mode",
        description: "Auto-approve operations without asking (overrides 'ask' permissions)",
        group: "general",
        control: "toggle",
        default: false,
        order: 5,
      },
      {
        key: "logLevel",
        label: "Log Level",
        description: "Verbosity of logging output",
        group: "general",
        control: "select",
        options: [
          { value: "debug", label: "Debug" },
          { value: "info", label: "Info" },
          { value: "warn", label: "Warning" },
          { value: "error", label: "Error" },
        ],
        default: "info",
        order: 6,
      },
      {
        key: "shell",
        label: "Shell",
        description: "Shell to use for bash commands",
        group: "general",
        control: "select",
        options: [
          { value: "bash", label: "Bash" },
          { value: "zsh", label: "Zsh" },
          { value: "pwsh", label: "PowerShell Core" },
          { value: "powershell", label: "Windows PowerShell" },
        ],
        default: "pwsh",
        order: 7,
      },
      {
        key: "logMaxSize",
        label: "Log Max Size (bytes)",
        description: "Maximum log file size before rotation (0 = disable rotation)",
        group: "general",
        control: "number",
        default: 10485760,
        validation: { min: 0, max: 1073741824 },
        order: 8,
      },
      {
        key: "logMaxFiles",
        label: "Log Max Files",
        description: "Number of rotated log files to keep",
        group: "general",
        control: "number",
        default: 5,
        validation: { min: 1, max: 100 },
        order: 9,
      },
    ],
  },
  {
    id: "providers",
    label: "Providers",
    icon: "cloud",
    description: "API keys, base URLs, and model configurations",
    fields: [
      {
        key: "providers",
        label: "Provider Configs",
        description: "Provider configurations keyed by name",
        group: "providers",
        control: "code",
        default: {},
        advanced: true,
        recordValue: {
          key: "",
          label: "Provider",
          group: "providers",
          control: "code",
          default: {},
          children: [
            { key: "apiKey", label: "API Key", group: "providers", control: "password", default: "", placeholder: "provider API key", validation: { secret: true } },
            { key: "baseUrl", label: "Base URL", group: "providers", control: "text", default: "", placeholder: "https://<endpoint>/v1" },
            { key: "headers", label: "Custom Headers", description: "HTTP headers keyed by header name (e.g. { \"X-Org\": \"my-org\" })", group: "providers", control: "code", default: {}, advanced: true },
            { key: "body", label: "Custom Body", description: "Extra JSON fields merged into request body", group: "providers", control: "code", default: {}, advanced: true },
            { key: "blacklist", label: "Model Blacklist", description: "Model IDs to hide from the picker (e.g. [\"model-id\"])", group: "providers", control: "code", default: [], advanced: true },
            { key: "whitelist", label: "Model Whitelist", description: "Only show these model IDs (empty = show all)", group: "providers", control: "code", default: [], advanced: true },
          ],
          validation: { fallback: { apiKey: "", baseUrl: "", headers: {}, body: {}, blacklist: [], whitelist: [] } },
        },
        validation: { fallback: {}, required: false },
      },
      {
        key: "webSearchApiKey",
        label: "Web Search API Key",
        description: "API key for web search (Tavily). Get one at https://tavily.com",
        group: "providers",
        control: "password",
        placeholder: "tvly-...",
        default: "",
        validation: { secret: true },
        order: 2,
      },
    ],
  },
  {
    id: "modelLimits",
    label: "Model Limits",
    icon: "sliders",
    description: "Token limits and pricing for models",
    advanced: true,
    fields: [
      {
        key: "maxTokens",
        label: "Max Tokens",
        description: "Maximum tokens per response",
        group: "modelLimits",
        control: "number",
        default: 4096,
        validation: { min: 1, max: 128000 },
        order: 1,
      },
      {
        key: "maxSteps",
        label: "Max Steps",
        description: "Maximum agentic iterations per run",
        group: "modelLimits",
        control: "number",
        default: 50,
        validation: { min: 1, max: 1000 },
        order: 2,
      },
      {
        key: "subagentDepth",
        label: "Subagent Depth",
        description: "Maximum depth of nested subagent calls",
        group: "modelLimits",
        control: "number",
        default: 3,
        validation: { min: 1, max: 10 },
        order: 3,
      },
      {
        key: "thinkingBudget",
        label: "Thinking Budget",
        description: "Tokens reserved for model reasoning (0 = disabled)",
        group: "modelLimits",
        control: "number",
        default: 0,
        validation: { min: 0, max: 128000 },
        order: 4,
      },
      {
        key: "thinkingPrompt",
        label: "Thinking Prompt",
        description: "System prompt prefix for thinking models",
        group: "modelLimits",
        control: "text",
        default: "",
        order: 5,
      },
      {
        key: "maxConcurrentToolCalls",
        label: "Max Concurrent Tool Calls",
        description: "Maximum parallel tool calls within a single step",
        group: "modelLimits",
        control: "number",
        default: 5,
        validation: { min: 1, max: 20 },
        order: 6,
      },
      {
        key: "maxToolCallsPerStep",
        label: "Max Tool Calls Per Step",
        description: "Maximum total tool calls allowed per step",
        group: "modelLimits",
        control: "number",
        default: 20,
        validation: { min: 1, max: 100 },
        order: 7,
      },
      {
        key: "stepTimeout",
        label: "Step Timeout (ms)",
        description: "Maximum time in milliseconds for a single step execution",
        group: "modelLimits",
        control: "number",
        default: 120000,
        validation: { min: 5000, max: 600000 },
        order: 8,
      },
      {
        key: "modelCacheTtlMs",
        label: "Model Cache TTL (ms)",
        description: "How long to cache model lists (e.g. OpenRouter discovery)",
        group: "modelLimits",
        control: "number",
        default: 300000,
        validation: { min: 10000, max: 86400000 },
        order: 9,
      },
    ],
  },
  {
    id: "modelRouting",
    label: "Model Routing",
    icon: "git-branch",
    description: "Model failover, per-feature routing, and advisor model",
    fields: [
      {
        key: "failover",
        label: "Failover Settings",
        group: "modelRouting",
        control: "code",
        default: {},
        description: "Ordered model failover chain: { enabled: true, models: [\"provider/model1\", \"provider/model2\"] }",
      },
      {
        key: "advisorModel",
        label: "Advisor Model",
        description: "Cheaper model for low-stakes tasks (title gen, file summaries)",
        group: "modelRouting",
        control: "text",
        placeholder: "provider/model-id",
        default: "",
      },
      {
        key: "perFeature",
        label: "Per-Feature Models",
        description: "Different models per feature: { chat: \"provider/model\", agent: \"provider/model\", tab: \"provider/model\" }",
        group: "modelRouting",
        control: "code",
        default: {},
        advanced: true,
      },
    ],
  },
  {
    id: "behaviour",
    label: "Behaviour",
    icon: "cpu",
    description: "How the agent behaves during task execution",
    fields: [
      {
        key: "selfCorrectOnFailure",
        label: "Self-Correct on Failure",
        description: "Automatically retry with error context when a step fails",
        group: "behaviour",
        control: "toggle",
        default: true,
        order: 1,
      },
      {
        key: "maxSelfCorrectAttempts",
        label: "Max Self-Correct Attempts",
        description: "How many times to retry before giving up",
        group: "behaviour",
        control: "number",
        default: 3,
        validation: { min: 1, max: 20 },
        order: 2,
      },
      {
        key: "autoApproval",
        label: "Auto-Approval Patterns",
        description: "Tool patterns to auto-approve without asking",
        group: "behaviour",
        control: "code",
        default: [],
        advanced: true,
        order: 3,
      },
      {
        key: "doomLoopThreshold",
        label: "Doom Loop Threshold",
        description: "Consecutive identical tool calls before loop detection kicks in (0 = disabled)",
        group: "behaviour",
        control: "number",
        default: 3,
        validation: { min: 0, max: 20 },
        order: 4,
      },
      {
        key: "shellDefaultTimeout",
        label: "Shell Default Timeout (ms)",
        description: "Default shell command timeout in milliseconds",
        group: "behaviour",
        control: "number",
        default: 30000,
        validation: { min: 1000, max: 300000 },
        order: 5,
      },
      {
        key: "shellMaxTimeout",
        label: "Shell Max Timeout (ms)",
        description: "Hard cap on shell command timeout in milliseconds",
        group: "behaviour",
        control: "number",
        default: 300000,
        validation: { min: 5000, max: 600000 },
        order: 6,
      },
      {
        key: "maxFileSize",
        label: "Max File Size (bytes)",
        description: "Maximum file size in bytes that read/write tools will handle",
        group: "behaviour",
        control: "number",
        default: 1048576,
        validation: { min: 1024, max: 104857600 },
        order: 7,
      },
    ],
  },
  {
    id: "permission",
    label: "Permissions",
    icon: "shield",
    description: "Fine-grained permission rules for tool access",
    fields: [
      {
        key: "externalDirectoryAccess",
        label: "External Directory Access",
        description: "Allow tools to read/write files outside the workspace directory without prompting",
        group: "permission",
        control: "toggle",
        default: false,
        order: 1,
      },
      {
        key: "permission",
        label: "Permission Rules",
        description: "Global permission rules keyed by tool name",
        group: "permission",
        control: "code",
        default: {},
        advanced: true,
      },
      {
        key: "permissionRiskDefaults",
        label: "Risk Defaults",
        description: "Default decisions per risk category: { \"read\": \"allow\", \"write\": \"ask\", \"bash\": \"ask\", \"glob\": \"allow\", \"grep\": \"allow\", \"browser\": \"ask\", \"network\": \"ask\", \"edit\": \"ask\" }",
        group: "permission",
        control: "code",
        default: {},
        validation: { fallback: {} },
        advanced: true,
      },
      {
        key: "allow",
        label: "Always Allow",
        description: "Tool patterns to always approve, e.g. [\"read(*.ts)\", \"glob(*)\", \"grep(*)\"]. Format: \"ToolName(glob)\"",
        group: "permission",
        control: "code",
        default: [],
        advanced: true,
      },
      {
        key: "deny",
        label: "Always Deny",
        description: "Tool patterns to always reject without asking, e.g. [\"bash(rm *)\", \"shell(rm *)\"]",
        group: "permission",
        control: "code",
        default: [],
        advanced: true,
      },
      {
        key: "ask",
        label: "Always Ask",
        description: "Tool patterns that always prompt for approval, e.g. [\"bash(*)\", \"write(**)\"]",
        group: "permission",
        control: "code",
        default: [],
        advanced: true,
      },
    ],
  },
  {
    id: "sandbox",
    label: "Sandbox",
    icon: "box",
    description: "Containerized execution environment for untrusted code",
    advanced: true,
    fields: [
      {
        key: "sandbox",
        label: "Sandbox Config",
        description: "Container sandbox settings: { mode: \"off\"|\"non-main\"|\"all\", scope: \"session\"|\"agent\"|\"shared\", timeoutMs: 30000, maxConcurrent: 3 }",
        group: "sandbox",
        control: "code",
        default: { mode: "off", scope: "session", timeoutMs: 30000, maxConcurrent: 3 },
        children: [
          { key: "mode", label: "Sandbox Mode", group: "sandbox", control: "select", default: "off", options: [{ value: "off", label: "Off" }, { value: "non-main", label: "Non-main agents only" }, { value: "all", label: "All execution" }] },
          { key: "scope", label: "Sandbox Scope", group: "sandbox", control: "select", default: "session", options: [{ value: "session", label: "Per session" }, { value: "agent", label: "Per agent" }, { value: "shared", label: "Shared sandbox" }] },
          { key: "timeoutMs", label: "Timeout (ms)", group: "sandbox", control: "number", default: 30000, validation: { min: 1000, max: 300000 } },
          { key: "maxConcurrent", label: "Max Concurrent", group: "sandbox", control: "number", default: 3, validation: { min: 1, max: 20 } },
        ],
      },
    ],
  },
  {
    id: "agents",
    label: "Agents",
    icon: "bot",
    description: "Custom agent definitions with model, prompt, and permission overrides",
    fields: [
      {
        key: "agents",
        label: "Agent Configs",
        description: "Agent configurations keyed by agent ID",
        group: "agents",
        control: "code",
        default: {},
        recordValue: {
          key: "",
          label: "Agent",
          group: "agents",
          control: "code",
          default: {},
        },
        advanced: true,
      },
      {
        key: "agentDirs",
        label: "Agent Directories",
        description: "Additional directories to scan for agent .md files",
        group: "agents",
        control: "code",
        default: [],
        advanced: true,
      },
    ],
  },
  {
    id: "skills",
    label: "Skills",
    icon: "book",
    description: "Skill discovery paths and settings",
    advanced: true,
    fields: [
      {
        key: "skills",
        label: "Skill Configs",
        description: "Skill configurations keyed by skill name",
        group: "skills",
        control: "code",
        default: {},
        advanced: true,
      },
      {
        key: "skillDirs",
        label: "Skill Directories",
        description: "Additional directories to search for SKILL.md files",
        group: "skills",
        control: "code",
        default: [],
        advanced: true,
      },
    ],
  },
  {
    id: "compaction",
    label: "Context Compaction",
    icon: "compress",
    description: "Controls how conversation history is compacted",
    advanced: true,
    fields: [
      {
        key: "compaction",
        label: "Compaction Config",
        description: "Context compaction settings",
        group: "compaction",
        control: "code",
        validation: { optional: true, fallback: {} },
        children: [
          {
            key: "strategy",
            label: "Strategy",
            description: "Compaction algorithm to use",
            group: "compaction",
            control: "select",
            options: [
              { value: "naive", label: "Naive (truncate oldest)" },
              { value: "llm", label: "LLM (summarize with model)" },
            ],
            default: "naive",
            validation: { fallback: "naive" },
          },
          {
            key: "headCount",
            label: "Head Messages",
            description: "Messages to preserve from the start",
            group: "compaction",
            control: "number",
            default: 3,
            validation: { min: 1 },
          },
          {
            key: "tailCount",
            label: "Tail Messages",
            description: "Messages to preserve from the end",
            group: "compaction",
            control: "number",
            default: 20,
            validation: { min: 1 },
          },
          {
            key: "tokenBudget",
            label: "Token Budget",
            description: "Target token count after compaction",
            group: "compaction",
            control: "number",
            default: 32000,
            validation: { min: 1000, max: 1000000 },
          },
          {
            key: "maxToolOutputLength",
            label: "Max Tool Output",
            description: "Maximum characters to keep from tool outputs",
            group: "compaction",
            control: "number",
            default: 500,
            validation: { min: 100 },
          },
          {
            key: "triggerThreshold",
            label: "Trigger Threshold",
            description: "Fraction of context window that triggers compaction (0.0-1.0, e.g. 0.75 = 75%)",
            group: "compaction",
            control: "number",
            default: 0.75,
            validation: { min: 0.1, max: 1.0 },
          },
          {
            key: "charsPerToken",
            label: "Chars Per Token",
            description: "Approximate characters per token for token estimation without a model tokenizer",
            group: "compaction",
            control: "number",
            default: 4,
            validation: { min: 1, max: 10 },
          },
        ],
      },
    ],
  },
  {
    id: "learning",
    label: "Learning & Memory",
    icon: "brain",
    description: "How the agent learns from past sessions",
    advanced: true,
    fields: [
      {
        key: "learning",
        label: "Learning Config",
        description: "Learning and memory settings",
        group: "learning",
        control: "code",
        validation: { optional: true },
        children: [
          { key: "enabled", label: "Enable Learning", group: "learning", control: "toggle", default: false },
          { key: "backgroundReview", label: "Background Review", group: "learning", control: "toggle", default: false },
          { key: "memoryWriteApproval", label: "Memory Write Approval", group: "learning", control: "toggle", default: true },
          { key: "skillWriteApproval", label: "Skill Write Approval", group: "learning", control: "toggle", default: true },
          {
            key: "memoryCharLimit",
            label: "Memory Char Limit",
            description: "Maximum characters for stored memories",
            group: "learning",
            control: "number",
            default: 2200,
            validation: { min: 100, max: 100000 },
          },
          {
            key: "userCharLimit",
            label: "User Char Limit",
            description: "Maximum characters for user-specific memories",
            group: "learning",
            control: "number",
            default: 1400,
            validation: { min: 100, max: 100000 },
          },
          { key: "autoMemoryEnabled", label: "Auto Memory", description: "Automatically store relevant context from completed sessions", group: "learning", control: "toggle", default: false },
          { key: "autoMemoryDirectory", label: "Auto Memory Directory", description: "Subdirectory within .vnt/ for auto-memory files", group: "learning", control: "text", default: "auto-memory", placeholder: "auto-memory" },
          { key: "autoMemoryMaxFiles", label: "Max Auto Memory Files", description: "Maximum number of auto-memory files to keep", group: "learning", control: "number", default: 20, validation: { min: 1, max: 500 } },
        ],
      },
    ],
  },
  {
    id: "indexing",
    label: "Codebase Indexing",
    icon: "search",
    description: "RAG indexing settings for codebase-aware context",
    advanced: true,
    fields: [
      {
        key: "indexing",
        label: "Indexing Config",
        description: "Codebase indexing for RAG: { enabled, ignore, maxFileSize, maxFiles, refreshInterval }",
        group: "indexing",
        control: "code",
        default: { enabled: true, ignore: ["node_modules/**", "dist/**", ".git/**"], maxFileSize: 100000, maxFiles: 500, refreshInterval: 3600 },
        children: [
          { key: "enabled", label: "Enable Indexing", group: "indexing", control: "toggle", default: true },
          { key: "ignore", label: "Ignore Patterns", description: "Glob patterns to exclude from indexing", group: "indexing", control: "code", default: ["node_modules/**", "dist/**", ".git/**"] },
          { key: "maxFileSize", label: "Max File Size (bytes)", group: "indexing", control: "number", default: 100000, validation: { min: 1000, max: 10000000 } },
          { key: "maxFiles", label: "Max Files", group: "indexing", control: "number", default: 500, validation: { min: 10, max: 10000 } },
          { key: "refreshInterval", label: "Refresh Interval (s)", description: "How often to re-index changed files in seconds", group: "indexing", control: "number", default: 3600, validation: { min: 60, max: 86400 } },
        ],
      },
    ],
  },
  {
    id: "mcp",
    label: "MCP Servers",
    icon: "plug",
    description: "Model Context Protocol server configurations",
    advanced: true,
    fields: [
      {
        key: "mcpServers",
        label: "MCP Server Configs",
        description: "MCP server configurations keyed by name",
        group: "mcp",
        control: "code",
        default: {},
        advanced: true,
      },
      {
        key: "mcpReconnectMaxRetries",
        label: "Reconnect Max Retries",
        description: "Maximum MCP reconnection attempts before giving up",
        group: "mcp",
        control: "number",
        default: 5,
        validation: { min: 0, max: 50 },
        advanced: true,
        order: 1,
      },
      {
        key: "mcpReconnectBaseDelayMs",
        label: "Reconnect Base Delay (ms)",
        description: "Initial delay between MCP reconnection attempts (doubles each retry)",
        group: "mcp",
        control: "number",
        default: 1000,
        validation: { min: 100, max: 60000 },
        advanced: true,
        order: 2,
      },
      {
        key: "mcpReconnectMaxDelayMs",
        label: "Reconnect Max Delay (ms)",
        description: "Maximum delay between MCP reconnection attempts",
        group: "mcp",
        control: "number",
        default: 30000,
        validation: { min: 1000, max: 300000 },
        advanced: true,
        order: 3,
      },
    ],
  },
  {
    id: "experimental",
    label: "Experimental",
    icon: "flask",
    description: "Experimental features that may change or break",
    advanced: true,
    fields: [
      {
        key: "experimental",
        label: "Experimental Settings",
        description: "Feature flags and experimental options",
        group: "experimental",
        control: "code",
        default: {},
      },
      {
        key: "noStore",
        label: "No Store Mode",
        description: "When enabled, no run events, session data, or logs are persisted to disk (privacy mode). Events still fire in-memory for tool runtime.",
        group: "experimental",
        control: "toggle",
        default: false,
        order: 1,
      },
      {
        key: "plugins",
        label: "NPM Plugins",
        description: "NPM plugin packages to auto-install and load (e.g. @vinhnt-sdk/plugin-mcp)",
        group: "experimental",
        control: "code",
        default: [],
        arrayItem: { key: "pluginName", label: "Package Name", group: "experimental", control: "text" },
        validation: { fallback: [] },
        advanced: true,
        order: 2,
      },
    ],
  },
  {
    id: "hooks",
    label: "Hooks & Automation",
    icon: "webhook",
    description: "Pre/post tool hooks, lint, test automation",
    advanced: true,
    fields: [
      {
        key: "hooks",
        label: "Tool Hooks",
        description: "Lifecycle hooks: { preToolUse: [{ matcher: \"ToolName(glob)\", command: \"script.sh\" }], postToolUse: [...], sessionStart: [...], sessionEnd: [...] }",
        group: "hooks",
        control: "code",
        default: { preToolUse: [], postToolUse: [], sessionStart: [], sessionEnd: [] },
        validation: { fallback: { preToolUse: [], postToolUse: [], sessionStart: [], sessionEnd: [] } },
      },
      {
        key: "lint",
        label: "Lint Configuration",
        group: "hooks",
        control: "code",
        default: { enabled: true, commands: {} },
        description: "Per-language lint commands: { enabled: true, commands: { \"typescript\": \"npx tsc --noEmit\", \"python\": \"ruff check\" } }",
      },
      {
        key: "test",
        label: "Test Configuration",
        group: "hooks",
        control: "code",
        default: { enabled: true, command: "" },
        description: "Test automation settings: { enabled: true, command: \"npm test\" }",
      },
      {
        key: "autoFix",
        label: "Auto-Fix",
        group: "hooks",
        control: "code",
        default: { enabled: false, maxAttempts: 3 },
        description: "Auto-fix on lint/test failure: { enabled: false, maxAttempts: 3 }",
      },
    ],
  },
  {
    id: "policies",
    label: "Policies",
    icon: "shield",
    description: "Structured permission rules with glob pattern matching for tool access",
    fields: [
      {
        key: "policies",
        label: "Policy Rules",
        description: "Tool permission rules with glob-based pattern matching",
        group: "policies",
        control: "code",
        validation: { optional: true, fallback: { defaultAction: "ask", rules: [] } },
        children: [
          {
            key: "defaultAction",
            label: "Default Action",
            description: "Default permission action when no rule matches",
            group: "policies",
            control: "select",
            options: [
              { value: "ask", label: "Ask (prompt user)" },
              { value: "allow", label: "Allow (auto-approve)" },
              { value: "deny", label: "Deny (auto-reject)" },
            ],
            default: "ask",
            validation: { fallback: "ask" },
            order: 1,
          },
          {
            key: "rules",
            label: "Rules",
            description: "Array of policy rule objects: { pattern: string, action: 'allow'|'ask'|'deny', args?: string }",
            group: "policies",
            control: "code",
            default: [],
            validation: { fallback: [] },
            order: 2,
          },
        ],
      },
    ],
  },
  {
    id: "lsp",
    label: "LSP",
    icon: "code",
    description: "Language Server Protocol configuration: auto-detect, diagnostics, custom servers",
    advanced: true,
    fields: [
      {
        key: "lsp",
        label: "LSP Config",
        description: "Language server auto-detection and diagnostics settings",
        group: "lsp",
        control: "code",
        validation: { optional: true, fallback: { autoDetect: true, diagnostics: true, servers: {} } },
        children: [
          {
            key: "autoDetect",
            label: "Auto-Detect Servers",
            description: "Automatically detect and start LSP servers based on project files",
            group: "lsp",
            control: "toggle",
            default: true,
            order: 1,
          },
          {
            key: "diagnostics",
            label: "Auto Diagnostics",
            description: "Auto-fetch diagnostics after each tool call (edit/write)",
            group: "lsp",
            control: "toggle",
            default: true,
            order: 2,
          },
          {
            key: "servers",
            label: "Custom Server Configs",
            description: "Custom LSP server configurations keyed by language (e.g. typescript, rust, python)",
            group: "lsp",
            control: "code",
            default: {},
            validation: { fallback: {} },
            advanced: true,
            order: 3,
          },
          {
            key: "poolIdleTimeoutMs",
            label: "Pool Idle Timeout (ms)",
            description: "How long an idle LSP server stays alive before shutdown",
            group: "lsp",
            control: "number",
            default: 300000,
            validation: { min: 10000, max: 3600000 },
            advanced: true,
            order: 4,
          },
          {
            key: "poolMaxRetries",
            label: "Pool Max Retries",
            description: "Maximum LSP server startup retry attempts",
            group: "lsp",
            control: "number",
            default: 3,
            validation: { min: 0, max: 20 },
            advanced: true,
            order: 5,
          },
          {
            key: "poolInitTimeoutMs",
            label: "Pool Init Timeout (ms)",
            description: "Timeout for LSP server initialization",
            group: "lsp",
            control: "number",
            default: 45000,
            validation: { min: 5000, max: 300000 },
            advanced: true,
            order: 6,
          },
          {
            key: "poolWaitDiagnosticsMs",
            label: "Pool Diag Timeout (ms)",
            description: "How long to wait for diagnostics after server init",
            group: "lsp",
            control: "number",
            default: 5000,
            validation: { min: 500, max: 60000 },
            advanced: true,
            order: 7,
          },
        ],
      },
    ],
  },
  {
    id: "notifications",
    label: "Notifications",
    icon: "bell",
    description: "Alert and notification preferences for runs and approvals",
    fields: [
      {
        key: "notifications",
        label: "Notification Config",
        description: "When and how to send notifications",
        group: "notifications",
        control: "code",
        validation: { optional: true, fallback: { enabled: true, onFailure: true, onApproval: true, onSuccess: false } },
        children: [
          {
            key: "enabled",
            label: "Enable Notifications",
            description: "Master switch for all notifications",
            group: "notifications",
            control: "toggle",
            default: true,
            order: 1,
          },
          {
            key: "onFailure",
            label: "On Failure",
            description: "Notify when a step fails",
            group: "notifications",
            control: "toggle",
            default: true,
            order: 2,
          },
          {
            key: "onApproval",
            label: "On Approval Request",
            description: "Notify when user approval is needed",
            group: "notifications",
            control: "toggle",
            default: true,
            order: 3,
          },
          {
            key: "onSuccess",
            label: "On Success",
            description: "Notify when a run completes successfully",
            group: "notifications",
            control: "toggle",
            default: false,
            order: 4,
          },
          { key: "soundEnabled", label: "Sound Enabled", description: "Play notification sounds", group: "notifications", control: "toggle", default: true, order: 5 },
          { key: "soundVolume", label: "Sound Volume", description: "Notification sound volume (0-100)", group: "notifications", control: "number", default: 70, validation: { min: 0, max: 100 }, order: 6 },
          { key: "desktop", label: "Desktop Notifications", description: "Show system-level desktop notifications", group: "notifications", control: "toggle", default: true, order: 7 },
          { key: "onError", label: "On Error", description: "Notify on runtime errors", group: "notifications", control: "toggle", default: true, order: 8 },
          { key: "onPermission", label: "On Permission Request", description: "Notify when tools request permissions", group: "notifications", control: "toggle", default: true, order: 9 },
        ],
      },
    ],
  },
  {
    id: "editor",
    label: "Editor",
    icon: "code",
    description: "Input editor behavior settings",
    fields: [
      {
        key: "editor",
        label: "Editor Config",
        description: "Input editor behavior: { vimMode: false, multiline: true, autoSuggest: true, tabCompletion: false }",
        group: "editor",
        control: "code",
        default: { vimMode: false, multiline: true, autoSuggest: true, tabCompletion: false },
        children: [
          { key: "vimMode", label: "Vim Mode", group: "editor", control: "toggle", default: false, order: 1 },
          { key: "multiline", label: "Multiline Input", description: "Allow multi-line input in chat", group: "editor", control: "toggle", default: true, order: 2 },
          { key: "autoSuggest", label: "Auto-Suggest", description: "Show auto-completion suggestions in input", group: "editor", control: "toggle", default: true, order: 3 },
          { key: "tabCompletion", label: "Tab Completion", description: "Tab key completes suggestions", group: "editor", control: "toggle", default: false, order: 4 },
        ],
      },
    ],
  },
  {
    id: "privacy",
    label: "Privacy",
    icon: "shield",
    description: "Telemetry, updates, and data sharing settings",
    advanced: true,
    fields: [
      {
        key: "privacy",
        label: "Privacy Config",
        description: "Telemetry and data sharing: { telemetry: true, autoUpdate: true, updateChannel: \"stable\", sessionSharing: \"manual\" }",
        group: "privacy",
        control: "code",
        default: { telemetry: true, autoUpdate: true, updateChannel: "stable", sessionSharing: "manual" },
        children: [
          { key: "telemetry", label: "Telemetry", description: "Send anonymous usage data", group: "privacy", control: "toggle", default: true, order: 1 },
          { key: "autoUpdate", label: "Auto Update", description: "Automatically install updates", group: "privacy", control: "toggle", default: true, order: 2 },
          { key: "updateChannel", label: "Update Channel", group: "privacy", control: "select", default: "stable", options: [{ value: "stable", label: "Stable" }, { value: "beta", label: "Beta" }], order: 3 },
          { key: "sessionSharing", label: "Session Sharing", group: "privacy", control: "select", default: "manual", options: [{ value: "manual", label: "Manual" }, { value: "auto", label: "Auto" }, { value: "disabled", label: "Disabled" }], order: 4 },
        ],
      },
    ],
  },
  {
    id: "network",
    label: "Network",
    icon: "globe",
    description: "HTTP proxy, request timeout, and retry settings",
    advanced: true,
    fields: [
      {
        key: "network",
        label: "Network Config",
        description: "HTTP proxy, timeouts, and retry settings for API calls",
        group: "network",
        control: "code",
        validation: { optional: true, fallback: { proxyEnabled: false, proxyUrl: "", timeout: 30000, maxRetries: 3 } },
        children: [
          {
            key: "proxyEnabled",
            label: "Proxy Enabled",
            description: "Enable HTTP/HTTPS proxy for all outbound requests",
            group: "network",
            control: "toggle",
            default: false,
            order: 1,
          },
          {
            key: "proxyUrl",
            label: "Proxy URL",
            description: "HTTP proxy URL (e.g. http://proxy:8080)",
            group: "network",
            control: "text",
            default: "",
            placeholder: "http://proxy:8080",
            order: 2,
          },
          {
            key: "timeout",
            label: "Request Timeout",
            description: "HTTP request timeout in milliseconds",
            group: "network",
            control: "number",
            default: 30000,
            validation: { min: 1000, max: 300000 },
            order: 3,
          },
          {
            key: "maxRetries",
            label: "Max Retries",
            description: "Maximum HTTP request retry attempts",
            group: "network",
            control: "number",
            default: 3,
            validation: { min: 0, max: 10 },
            order: 4,
          },
          {
            key: "webSearchNumResults",
            label: "Web Search Results",
            description: "Default number of results to return from web search",
            group: "network",
            control: "number",
            default: 5,
            validation: { min: 1, max: 20 },
            order: 5,
          },
          {
            key: "webFetchMaxResponseSize",
            label: "Web Fetch Max Response (bytes)",
            description: "Maximum response size in bytes for web fetch tool",
            group: "network",
            control: "number",
            default: 524288,
            validation: { min: 1024, max: 10485760 },
            order: 6,
          },
        ],
      },
    ],
  },
  {
    id: "keybinds",
    label: "Keyboard Shortcuts",
    icon: "keyboard",
    description: "Custom keyboard shortcut mappings for the TUI",
    advanced: true,
    fields: [
      {
        key: "keybinds",
        label: "Shortcut Mappings",
        description: "Keyboard shortcut configurations keyed by action name (e.g. { \"submit\": \"Ctrl+Enter\", \"cancel\": \"Escape\" })",
        group: "keybinds",
        control: "code",
        default: {},
        advanced: true,
      },
    ],
  },
  {
    id: "themes",
    label: "Themes & UI",
    icon: "palette",
    description: "Color scheme, theme mode, and UI appearance customization",
    advanced: true,
    fields: [
      {
        key: "theme",
        label: "Theme Config",
        description: "Color scheme and UI appearance settings",
        group: "themes",
        control: "code",
        validation: { optional: true, fallback: { mode: "dark", colors: {} } },
        children: [
          {
            key: "mode",
            label: "Theme Mode",
            description: "Base color scheme for the UI",
            group: "themes",
            control: "select",
            options: [
              { value: "dark", label: "Dark" },
              { value: "light", label: "Light" },
              { value: "auto", label: "Auto (follow system)" },
            ],
            default: "dark",
            validation: { fallback: "dark" },
            order: 1,
          },
          {
            key: "colors",
            label: "Color Overrides",
            description: "Custom color overrides keyed by token name (e.g. { primary: \"#007acc\", error: \"#f44747\" })",
            group: "themes",
            control: "code",
            default: {},
            advanced: true,
            order: 2,
          },
          {
            key: "fontFamily",
            label: "Font Family",
            description: "Code font family for messages and editors",
            group: "themes",
            control: "select",
            default: "roboto",
            options: [{ value: "roboto", label: "Roboto" }, { value: "inter", label: "Inter" }, { value: "monospace", label: "Monospace" }, { value: "jetbrains-mono", label: "JetBrains Mono" }, { value: "fira-code", label: "Fira Code" }, { value: "source-code-pro", label: "Source Code Pro" }],
            order: 3,
          },
          { key: "showThinkingBlocks", label: "Show Thinking Blocks", description: "Display model reasoning blocks in chat", group: "themes", control: "toggle", default: true, order: 4 },
          { key: "compactMode", label: "Compact Mode", description: "Use tighter spacing in chat UI", group: "themes", control: "toggle", default: false, order: 5 },
          {
            key: "diffStyle",
            label: "Diff Style",
            description: "Visual style for code diffs",
            group: "themes",
            control: "select",
            default: "inline",
            options: [{ value: "inline", label: "Inline" }, { value: "split", label: "Split" }, { value: "stacked", label: "Stacked" }],
            order: 6,
          },
          {
            key: "borderRadius",
            label: "Border Radius",
            description: "UI border radius preset",
            group: "themes",
            control: "select",
            default: "md",
            options: [{ value: "sm", label: "Small (4px)" }, { value: "md", label: "Medium (6px)" }, { value: "lg", label: "Large (8px)" }],
            order: 7,
          },
        ],
      },
    ],
  },
  {
    id: "commands",
    label: "Custom Commands",
    icon: "terminal",
    description: "Custom command aliases and shortcuts for the CLI",
    advanced: true,
    fields: [
      {
        key: "commands",
        label: "Command Aliases",
        description: "Custom command aliases keyed by shortcut name (e.g. { \"deploy\": \"pnpm build && pnpm publish\" })",
        group: "commands",
        control: "code",
        default: {},
        advanced: true,
      },
    ],
  },
  {
    id: "formatters",
    label: "Formatters",
    icon: "wand",
    description: "Code formatter configuration per language",
    advanced: true,
    fields: [
      {
        key: "formatters",
        label: "Formatter Configs",
        description: "Formatter configurations keyed by language (e.g. { \"typescript\": { command: \"prettier\", args: [\"--write\"] } })",
        group: "formatters",
        control: "code",
        default: {},
        advanced: true,
      },
    ],
  },
  {
    id: "modes",
    label: "Behaviour Modes",
    icon: "sliders",
    description: "Agent behaviour mode profiles (Plan = read-only, Build = full access)",
    fields: [
      {
        key: "defaultMode",
        label: "Default Mode",
        description: "Default behaviour mode when starting a session",
        group: "modes",
        control: "select",
        options: [
          { value: "build", label: "Build (full access)" },
          { value: "plan", label: "Plan (read-only)" },
        ],
        default: "build",
      },
      {
        key: "modeProfiles",
        label: "Custom Mode Profiles",
        description: "Define custom behaviour mode profiles. Each key is a mode name, value is a rules array: { rules: [{ effect: \"allow\"|\"deny\", target: \"tool.*\" }] }",
        group: "modes",
        control: "code",
        default: {},
        validation: { fallback: {} },
        advanced: true,
      },
    ],
  },
  {
    id: "managed",
    label: "Managed Settings",
    icon: "building",
    description: "Organization-managed settings and restrictions (admins only)",
    advanced: true,
    fields: [
      {
        key: "managed",
        label: "Managed Config",
        description: "Organization-managed settings: { enabled: false, allowedModels: [], allowedMcpServers: [], deniedMcpServers: [], minVersion: \"1.0.0\", forceLoginOrgId: \"\" }",
        group: "managed",
        control: "code",
        default: { enabled: false, allowedModels: [], allowedMcpServers: [], deniedMcpServers: [], minVersion: "", forceLoginOrgId: "" },
      },
    ],
  },
  {
    id: "audit",
    label: "Audit Logging",
    icon: "file-text",
    description: "Compliance audit trail configuration",
    advanced: true,
    fields: [
      {
        key: "audit",
        label: "Audit Config",
        description: "Audit logging: { enabled: false, logPath: \"\", retentionDays: 90, logLevel: \"info\" }",
        group: "audit",
        control: "code",
        default: { enabled: false, logPath: "", retentionDays: 90, logLevel: "info" },
      },
    ],
  },
];
