export type { VntConfig, ProviderConfig, LearningConfig, CompactionConfig, PermissionRuleConfig, PolicyConfig, PolicyRuleConfig, LspConfig, NotificationConfig, NetworkConfig, ThemeConfig } from "./schema.js";
export { validateConfig, DEFAULT_LEARNING } from "./schema.js";
export { resolveConfig } from "./resolver.js";
export { parseJsonc } from "./jsonc.js";
export { loadConfig } from "./loader.js";
export { getConfigFilePaths } from "./loader.js";
export type { ConfigSource, LoadedConfig } from "./loader.js";
export { mergeConfig, deepMerge } from "./merge.js";
export { parseYaml, isYamlFile } from "./yaml.js";
export { createConfigWatcher } from "./config-watcher.js";
export type { ConfigWatcher, ConfigWatcherOptions, ConfigFileChangeListener } from "./config-watcher.js";
export { EnvConfigSource, ConfigPriority } from "./providers/env-provider.js";
export type { ConfigSource as ProviderConfigSource } from "./providers/env-provider.js";
export { detectProjectLayout, detectCompatDirs, hasVntInfrastructure } from "./project-detector.js";
export type { SourceDir, ProjectLayout } from "./project-detector.js";
export { CONFIG_GROUPS } from "./definition.js";
export type { ConfigFieldMeta, ControlType, ConfigGroup } from "./definition.js";
export { buildVntConfigSchema, flattenDefinition, getGroupById } from "./schema-gen.js";
export { buildVntJsonSchema } from "./json-schema-gen.js";
export type { JsonSchemaProperty, JsonSchemaRoot } from "./json-schema-gen.js";
export { MigrationRegistry, createDefaultMigrationRegistry } from "./migration.js";
export type { ConfigMigration, MigrationEntry } from "./migration.js";
export { loadEnvFile, findEnvFile, ensureVntApiToken } from "./env-loader.js";
